library(httptest2)

Sys.setenv(PLUTO_ENV="staging")

# Read project .Renviron file to get test env vars
TESTTHAT_API_TOKEN <- Sys.getenv("PLUTO_TEST_API_TOKEN")
TESTTHAT_INVALID_API_TOKEN <- Sys.getenv("PLUTO_INVALID_API_TOKEN")

TESTTHAT_EMPTY_PROJ_ID <- Sys.getenv("EMPTY_PROJECT_ID")
TESTTHAT_NONEMPTY_PROJ_ID <- Sys.getenv("NONEMPTY_PROJECT_ID")
NUM_PROJ_EXPTS <- 5

TESTTHAT_EXPT_ID_RNASEQ <- Sys.getenv("EXPERIMENT_ID_RNASEQ")

TESTTHAT_PLOT_ID_PCA <- Sys.getenv("PLOT_ID_PCA")
TESTTHAT_PLOT_ID_DE_VOLCANO_V2 <- Sys.getenv("PLOT_ID_DE_VOLCANO_V2")

