library(httptest2)

# Read project .Renviron file to get test env vars
TESTTHAT_API_TOKEN <- Sys.getenv("PLUTO_API_TOKEN")
TESTTHAT_INVALID_API_TOKEN <- Sys.getenv("INVALID_API_TOKEN")
TESTTHAT_EXPT_ID <- Sys.getenv("EXPERIMENT_ID")
TESTTHAT_EXPT_ID_RNASEQ <- Sys.getenv("EXPERIMENT_ID_RNASEQ")
TESTTHAT_PCA_PLOT_ID <- Sys.getenv("PCA_PLOT_ID")
TESTTHAT_DB_VOLCANO_PLOT_V2_ID <- Sys.getenv("DB_VOLCANO_PLOT_V2_ID")
TESTTHAT_DE_VOLCANO_PLOT_V2_ID <- Sys.getenv("DE_VOLCANO_PLOT_V2_ID")
TESTTHAT_PROJ_ID <- Sys.getenv("PROJECT_ID")
