library(httptest2)

Sys.setenv(PLUTO_ENV="staging")

# Read project .Renviron file to get test env vars
TESTTHAT_API_TOKEN <- Sys.getenv("PLUTO_TEST_API_TOKEN")
TESTTHAT_INVALID_API_TOKEN <- Sys.getenv("PLUTO_INVALID_API_TOKEN")

NUM_PROJS <- 4
TESTTHAT_EMPTY_PROJ_ID <- Sys.getenv("EMPTY_PROJECT_ID")
TESTTHAT_NONEMPTY_PROJ_ID <- Sys.getenv("NONEMPTY_PROJECT_ID")
NUM_ALL_EXPTS <- 6
NUM_PROJ_EXPTS <- 5

# RNA-seq test experiment
TESTTHAT_EXPT_ID_RNASEQ <- Sys.getenv("EXPERIMENT_ID_RNASEQ")
NUM_ANALYSES_RNASEQ <- 13
NUM_EXPT_SAMPLES_RNASEQ <- 153
NUM_EXPT_TARGETS_RNASEQ <- 15892
NUM_DE_TARGETS_RNASEQ <- 8270
TESTTHAT_PLOT_ID_PCA <- Sys.getenv("PLOT_ID_PCA")
TESTTHAT_PLOT_ID_DE_VOLCANO_V2 <- Sys.getenv("PLOT_ID_DE_VOLCANO_V2")

# CUT&RUN test experiment
TESTTHAT_EXPT_ID_CUTANDRUN <- Sys.getenv("EXPERIMENT_ID_CUTANDRUN")
NUM_ANALYSES_CUTANDRUN <- 2
TESTTHAT_PLOT_ID_DB_VOLCANO_V2 <- Sys.getenv("PLOT_ID_DB_VOLCANO_V2")
NUM_DB_TARGETS_CUTANDRUN <- 49916

# Experiment for creating/modifying analyses
TESTTHAT_EXPT_ID_MOD <- Sys.getenv("EXPERIMENT_ID_MOD")
